language: php

sudo: false

git:
  submodules: true

php:
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - ~/.composer/cache/files
    - vendor
    - node_modules

before_install:
  - composer self-update --no-interaction

install:
  - composer install

before_script:

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false